about/index.html
documentation/cocoapods/index.md
documentation/index.md
index.html

I also found via this [validator](https://validator.w3.org/nu/?doc=http%3A%2F%2Fsparkle-project.org) that it doesn't like the unordered list element inside the paragraph for the icons at the bottom. Maybe the ul should have the "icons" class instead? I don't have jekyll installed so didn't test if that would work. But apparently lists can't be inside paragraphs as paragraphs can't contain other block elements (from what I read).

Various minor fixes

---

documentation/index.md

This is to address #19 
Feel free to alter it, give more flare, or whatever else.

Add note about App Transport Security

---

css/main.scss

This is somewhat jokey, but that super light text is really hard on the eyes. Maybe more of a discussion point than something I’d expect you to merge.
I didn’t test building the site because I could not find any instructions.

Make text easier to read

---

documentation/customization/index.md

Super useful, previously undocumented key for shared settings in app groups 👍

add SUDefaultsDomain description

---

_sass/bootstrap/_navbar.scss
css/main.scss
index.html

[Modifications]
Top Section
- Screenshot
- Download + Cocoapod Buttons
- Tag-line
- Navbar
Features Section
- Integrated beautiful cards + Transitions
- Card Hover Effect
Users Section
- Background color
- Fonts size
Footer & Users  Section
- Font
- Icon Hover Effect
Overall
- Overall Text (Home, About, Documentation)
- Add Browser Prefixes
- Beautified Code
Tested: ✅

👨‍🎨 Beautified Sparkle Website 🎉

---

documentation/index.md
documentation/sandboxing/index.md

Regarding https://github.com/sparkle-project/Sparkle/issues/1814

Update instructions documentation on sandboxing / XPC Services

---

documentation/sandboxing/index.md

See https://github.com/sparkle-project/Sparkle/pull/1823

Update XPC Service signing instructions to reflect latest changes

---

documentation/customization/index.md
documentation/index.md
documentation/programatic-setup/index.md

Show example of setting up Sparkle programmatically and relevant APIs
Update API page a bit (I want an actual API reference documentation at some point..)

Document and show example of starting Sparkle programmatically

---

_config.yml

Use rouge highlighter theme and GFM for syntax highlighting.

Use rouge highlighter theme and GFM

---

.github/workflows/update-api-reference.yml

Add GitHub action to update API Reference documentation

---

documentation/system-profiling/index.md

Add documentation for system profile privacy

Add documentation for system profile privacy

---

documentation/publishing/index.md

Document that web servers can customize the feed based on http request / data.

Document that web servers can customize the feed

---

documentation/delta-updates/index.md

Also clarify compatibility requirements.

Fix broken URL references for delta updates

---

documentation/eddsa-migration/index.md
documentation/index.md
documentation/package-updates/index.md
documentation/preferences-ui/index.md
documentation/programmatic-setup/index.md
documentation/publishing/index.md
documentation/sandboxing/index.md
documentation/upgrading/index.md
index.html

Holding onto these documentation changes until official release.

Update documentation for official Sparkle 2 release

---

documentation/publishing/index.md

Add documentation for file system / HFS+ level compression

---

documentation/preferences-ui/index.md

Recommend binding to file owner's updater for preferences UI

---

documentation/gentle-reminders/index.md

This is the documentation page for https://github.com/sparkle-project/Sparkle/pull/2122

Add initial documentation for gentle reminders

---

documentation/index.md
documentation/programmatic-setup/index.md

Document hurdles around enabling library validation

---

documentation/customization/index.md
documentation/index.md
documentation/preferences-ui/index.md
documentation/programmatic-setup/index.md

We provide a more sound SwiftUI sample and also show how to add user settings to a SwiftUI app.

Revamp and improve SwiftUI programmatic samples

---

documentation/delta-updates/index.md

Add documentation for new deltaFrom attributes in Sparkle 2.3

---

documentation/publishing/index.md
documentation/upgrading/index.md
index.html

Upgrade minimum system version and migration for 2.3
