index.html

- Updated download link to reference latest release available on GitHub.
- Removed version specific notes as these are available with each release on GitHub.

Updated to always reference latest Sparkle release

---

index.html

Sparkle does not require a Cocoa based project.

Switched from 'Cocoa' to 'Mac' developers.

---

documentation/index.md
documentation/publishing/index.md

This updates Sparkle's security documentation to reflect the current
codebase. More weight is now given to https and DSA signatures, and
more info is given on how Sparkle uses code signing.
Feel free to improve wording / give suggestions..

Update Security Documentation

---

documentation/index.md

It's easier to use the "Runpath Search Paths" setting instead of "Other Linker Flags". I kept the full flag for non-Xcode projects (CMake, Qt, etc).

Prefer "Runpath Search Paths" build setting

---

_layouts/default.html

Redirect bots and users from https://sparkle-project.github.io to the official domain + tiny tweaks.

Canonical links

---

_layouts/default.html

We are shutting down the Bandwidth Hog brand and migrating everything over to the MaxCDN brand.

Updated the Sponsored By text and links.

---

documentation/index.md

This takes app translocation in macOS 10.12 and later into account. This may not be relevant to Sparkle completely (just like how App Transport Security isn't), but this will trip up developers that aren't aware of App Translocation, so it is probably worth bringing up.
See second half of the WWDC video for "What's New in Security" on the details regarding app translocation: https://developer.apple.com/videos/play/wwdc2016/706/
Apple is going to be pushing pretty hard on distributing dmg's and code signing them. Feel free to make suggestions with wording or where it should be placed or what not else.

Add recommentation to distributing apps on a dev's website

---

documentation/cocoapods/index.md

Only thing I'm going to note is that I believe `use_frameworks!` should be used, although I'm not entirely familiar with Cocoapods myself. It's not enabled by default though because iOS required static libraries for a long time. However in our case we don't have a static library which I think is uncommon for Mac libraries. Also anybody using Swift needs to use this setting as well. If `use_frameworks!` isn't used, then cocoa pods embeds an unnecessary static library as far as I can tell.

Updating Cocoapods docs

---

documentation/index.md

The step 0, while important, is not directly about installing the framework, and it doesn't have to be the first thing the user does.
The part about making archives really fits better in the flow when user needs to make the archive. I think it's better if we first direct users to get Sparkle installed, and then go into details how to make it work best.

Move section 0 to more natural place in the flow

---

documentation/index.md

After searching for a while on how to link the release notes file to the appcast.xml automatically, I think it would be nice to have it on the index page.

Add instructions about releaseNotesLink

---

_layouts/documentation-v2.html
documentation/v2/index.md

As a first step to get started with the docs for Sparkle 2.x, this PR adds a tab bar to the documentation section for switching between the docs for Sparkle 1.x and Sparkle 2.x.
Docs for Sparkle 2.x go into a subfolder (/documentation/v2/). They have a separate layout (`documentation-v2`), so we can easily add banners to outdated documentation pages in the future.

Add section for Sparkle 2.x documentation

---

documentation/index.md

Markdown considers numbered and bulleted lists totally separately, which gummed things up here. Adding blank lines fixes it.

Fix bulleted list rendering

---

documentation/customization/index.md
documentation/publishing/index.md

This is the documentation update that goes along with a feature update for which there is a corresponding pull request in the Sparkle project.
Allow an individual appcast to override the SUAutomaticallyUpdate user defaults setting and prevent the new version from being installed automatically. This is helpful if the version referenced by the appcast is a paid upgrade that should not be applied without an explicit user decision. To use this feature, the new appcast property "sparkle:doNotAutomaticallyUpdate" shall be set to 1 or YES.

Allow an appcast to prevent the new version from being installed automatically

---

documentation/publishing/index.md

It now supports this on top of 2.x branch.

Remove note that Sparkle 2 doesn't support minimumAutoupdateVersion

---

documentation/package-updates/index.md
documentation/upgrading/index.md

What `placeholder-version` can I use? I.e, do we have an expected version we can guarantee the support will be in or will we need to hold onto this PR until it ships?
Unrelated specifically to this (but with timing consideration), I want to switch the default development branch to 2.x pretty soon but probably not until after 1.25.0 is released. If this specific feature we want to slate for 1.26.0 and the 2.x dev branch switch is done before 1.26.0 (likely small release) that would technically still be okay.

Document support and migration path for non-archived pkg or mpkg updates

---

documentation/bundles/index.md
documentation/customization/index.md
documentation/delta-updates/index.md
documentation/publishing/index.md
documentation/sandboxing/index.md
documentation/upgrading/index.md
files/sparkletestcast.xml

* Plug-in bundles & Sandboxing
* Javascript key
* sparkle:version element over attribute changes
* <link> additions (in case Sparkle uses them to fall back on, eg update not found)
* Major upgrades
* Minimum system requirement for 2.x
Several changes I had lying around here locally for some time, just added sparkle:version changes.

Update documentation (part 1)

---

documentation/delta-updates/index.md
documentation/index.md
documentation/publishing/index.md
documentation/upgrading/index.md

* Swift Package Manager
* Informational updates (2.x)
* Critical updates
* Phased Group Rollouts
* sparkle:maximumSystemVersion
Added migration notes for:
* not allowing downgrades
* SPARKLE_BUILD_UI_BITS instead of SparkleCore
Added note for previous sparkle:version recommendation.
Minor additional changes (adding Publishing an update link to bottom of docs page, improving CFBundleVersion link to official source).

Add documentation for missing features

---

documentation/eddsa-migration/index.md
documentation/index.md
documentation/publishing/index.md
documentation/sandboxing/index.md
documentation/upgrading/index.md

* EdDSA migration from DSA
* No EdDSA deprecation
* Channels
* Setting feed programmatically
* Migrating to newer features using new appcast (linked from EdDSA migration)
* Extending the Appcast with custom extensions
* Migration notes from earlier versions of Sparkle 2
* Minor rewording on some pages

Update documentation for several recent features

---

documentation/bundles/index.md
documentation/customization/index.md
documentation/delta-updates/index.md
documentation/eddsa-migration/index.md
documentation/index.md
documentation/preferences-ui/index.md
documentation/programatic-setup/index.md
documentation/publishing/index.md
documentation/sandboxing/index.md
documentation/sparkle-cli/index.md
documentation/upgrading/index.md

Easier to review with [whitespace changes hidden](https://github.com/sparkle-project/sparkle-project.github.io/pull/77/files?diff=unified&w=1). I wasn't able to test locally, though, because the layouts didn't load, and I don't know if that's just a problem with my local Jekyll, or what.
```
$ jekyll serve
Configuration file: none
Source: /Users/zev/Projects/sparkle-project.github.io/documentation
Destination: /Users/zev/Projects/sparkle-project.github.io/documentation/_site
Incremental build: disabled. Enable with --incremental
Generating... 
Build Warning: Layout 'documentation' requested in index.md does not exist.
Build Warning: Layout 'documentation' requested in eddsa-migration/index.md does not exist.
Build Warning: Layout 'documentation' requested in system-profiling/index.md does …
```

Add syntax highlighting to code snippets

---

css/main.scss
documentation/publishing/index.md

Add CSS style tags for syntax highlighting.
Using https://github.com/richleland/pygments-css/blob/master/friendly.css

Add CSS style tags for syntax highlighting

---

documentation/index.md

Show where to find auxiliary tools and XPC Services via SPM
Update state of pre-releases via package management and Sparkle 2 beta releases.

Update setup guide for pre-releases and improve SPM docs

---

documentation/eddsa-migration/index.md
documentation/index.md

Clarify Sparkle 2 needed for understanding EdDSA keys.
Sparkle 1.27 is now released.
Clarify importance of keeping keys safe and not losing them.

Improve EdDSA migration documentation

---

documentation/package-updates/index.md

Documentation guide should cater to newer users and new functionality first most.

Recommend using bare package installations first

---

documentation/sandboxing/index.md

Update documentation for re-signing Sparkle and its services manually, if we re-enable get-task-allow entitlements.

Update documentation for re-signing Sparkle and its services manually

---

documentation/index.md

Because disk images are very slow / unreliable and package installers should be used in rare cases.

Recommend zip and tarball formats more strongly

---

documentation/index.md
documentation/sandboxing/index.md

Clarify the purpose of requiring CFBundleVersion.
Clarify in Testing that debugging issue shouldn't happen with workflow we suggest.

Add documentation clarification

---

css/main.scss
documentation/index.md
index.html

Replace CocoaPods button on main webpage with link to Basic setup.
Clarify that Sparkle tools are not included in Carthage package.

Update package management details

---

documentation/delta-updates/index.md
documentation/index.md
documentation/publishing/index.md

* Update delta documentation to include metadata specification.
* Update mentions of archives to encourage/suggest LZMA (.tar.xz)
* Note 2.1 beta publishing features for informational updates and major upgrades

Update documentation for Sparkle 2.1 beta

---

documentation/package-updates/index.md

Deprecate interactive based package installations more boldly. Recommend bare based package updates more bodly. Remove compatibility implications for guided archive based updates because they most people are not using interactive based pkg updates.

Modernize documentation for package based updates

---

documentation/upgrading/index.md

Also update upgrading page so that we specify the version that is being upgraded to rather than versions that are being upgraded from, which was more confusing.

Add deprecation notice for signing key

---

documentation/index.md
documentation/sandboxing/index.md

Break the sandboxing page into components rather than XPC Services. XPC Services should no longer be emphasized for the Communication component because it is much more likely for apps to implement the entitlements rather than the XPC Services.

Improve clarification on sandboxing documentation
